import { Jugador, Match } from "./types";

export const MORON_TEAM_ID = "hbba";

export const SITE_URL =
  process.env.NEXT_PUBLIC_SITE_URL ?? "https://juegamoron.vercel.app";

export const EMPTY_MATCH: Match = {
  versus: "",
  estadio: "",
  isAway: false,
  id_prom: "",
  datetime: "",
  ficha_partido: "",
  ficha_rival: "",
  youtube: "",
  result: "",
  competencia: "",
  fecha: "",
};

export const JUGADORES: Jugador[] = [
  { nombre: "Lucas", apellido: "ABASCIA" },
  { nombre: "Ramón", apellido: "ABILA" },
  {
    nombre: "Marcos",
    apellido: "ACUÑA",
    clubes: [{ nombre: "Deportivo Morón" }, { nombre: "Centro Español" }],
  },
  { nombre: "Gastón", apellido: "ADA" },
  { nombre: "Damián", apellido: "ADIN" },
  { nombre: "Damián", apellido: "AKERMAN" },
  { nombre: "Agustín", apellido: "ALLIONE" },
  { nombre: "Mauricio", apellido: "ALONSO" },
  { nombre: "Leonel", apellido: "ALTOBELLI" },
  { nombre: "Fabricio", apellido: "ALVARENGA" },
  { nombre: "Iván", apellido: "ALVAREZ" },
  { nombre: "Milton", apellido: "ALVAREZ" },
  { nombre: "Lucas", apellido: "ANGELINI" },
  { nombre: "Nicolás", apellido: "ANGELLOTTI" },
  {
    nombre: "Rodrigo",
    apellido: "ARCIERO",
    clubes: [
      { nombre: "Deportivo Morón" },
      { nombre: "Excursionistas" },
      { nombre: "Huracán LH" },
      { nombre: "Inter" },
      { nombre: "SJK Seinäjoki" },
      { nombre: "Banfield" },
      { nombre: "Patronato" },
      { nombre: "Independiente Rivadavia" },
      { nombre: "Talleres" },
      { nombre: "All Boys" },
    ],
  },
  { nombre: "Ramiro", apellido: "ARIAS" },
  { nombre: "Josué", apellido: "AYALA" },
  { nombre: "Maximiliano", apellido: "BADUR" },
  {
    nombre: "Facundo",
    apellido: "BAEZ",
    clubes: [{ nombre: "Deportivo Morón" }, { nombre: "San Telmo" }],
  },
  { nombre: "Guillermo", apellido: "BAEZ" },
  { nombre: "Gonzalo", apellido: "BAGLIVO" },
  {
    nombre: "Matias",
    apellido: "BALLINI",
    clubes: [
      { nombre: "Deportivo Morón" },
      { nombre: "Curicó Unido" },
      { nombre: "Cobreloa" },
      { nombre: "San Martín (Tucumán)" },
      { nombre: "Independiente Santa Fe" },
      { nombre: "Villa Dálmine" },
      { nombre: "Atlético Tucumán" },
      { nombre: "Colón" },
      { nombre: "Rosario Central" },
      { nombre: "Girona" },
    ],
  },
  {
    nombre: "Fernando",
    apellido: "BARRIENTOS",
    clubes: [
      { nombre: "Deportivo Morón" },
      { nombre: "Valletta" },
      { nombre: "Gimnasia (Jujuy)" },
      { nombre: "All Boys" },
      { nombre: "Cobreloa" },
      { nombre: "Lanús" },
      { nombre: "Guaraní" },
      { nombre: "Defensa y Justicia" },
      { nombre: "Atlético Paranaense" },
      { nombre: "Rosario Central" },
    ],
  },
  { nombre: "Diego", apellido: "BARRIOS" },
  { nombre: "Rodrigo", apellido: "BASUALDO" },
  { nombre: "Javier", apellido: "BAYK" },
  {
    nombre: "Matias",
    apellido: "BENITEZ",
    clubes: [
      { nombre: "Deportivo Morón" },
      { nombre: "Central Córdoba (SdE)" },
      { nombre: "Racing (Montevideo)" },
      { nombre: "Arsenal" },
      { nombre: "San Martín (San Juan)" },
    ],
  },
  {
    nombre: "Jonathan",
    apellido: "BERON",
    clubes: [
      { nombre: "Deportivo Morón" },
      { nombre: "Tristán Suárez" },
      { nombre: "Vélez" },
      { nombre: "Estudiantes (Caseros)" },
      { nombre: "Defensa y Justicia" },
    ],
  },
  { nombre: "Ariel", apellido: "BERON" },
  { nombre: "Fernando", apellido: "BERSANO" },
  {
    nombre: "Gonzalo",
    apellido: "BERTERAME",
    clubes: [
      { nombre: "Deportivo Morón" },
      { nombre: "San Martín (San Juan)" },
      { nombre: "Estudiantes (Caseros)" },
      { nombre: "Atlanta" },
      { nombre: "Gimnasia (Mendoza)" },
      { nombre: "San Lorenzo" },
    ],
  },
  {
    nombre: "Mariano",
    apellido: "BITTOLO",
    clubes: [
      { nombre: "Deportivo Morón" },
      { nombre: "Newell's" },
      { nombre: "Atromitos" },
      { nombre: "Argentinos Juniors" },
      { nombre: "Colón" },
      { nombre: "Albacete" },
      { nombre: "Vélez" },
      { nombre: "Córdoba" },
    ],
  },
  { nombre: "Maximiliano", apellido: "BONANNO" },
  { nombre: "Leonel", apellido: "BONTEMPO" },
  {
    nombre: "Mariano",
    apellido: "BRACAMONTE",
    clubes: [
      { nombre: "Deportivo Morón" },
      { nombre: "Deportivo Riestra" },
      { nombre: "UAI Urquiza" },
    ],
  },
  { nombre: "Maximiliano", apellido: "BRITO" },
  { nombre: "Gustavo Daniel", apellido: "BRITOS" },
  { nombre: "Cristian", apellido: "BROGGI" },
  { nombre: "Mateo", apellido: "BROGLIA" },
  { nombre: "Hernan", apellido: "BRUNO" },
  {
    nombre: "Mauro",
    apellido: "BURRUCHAGA",
    clubes: [
      { nombre: "Deportivo Morón" },
      { nombre: "Albion" },
      { nombre: "Arsenal" },
      { nombre: "Chievo" },
      { nombre: "Deportivo Maldonado" },
    ],
  },
  { nombre: "Mario", apellido: "BUSTOS" },
  { nombre: "Mauro", apellido: "BUSTOS" },
  { nombre: "Bruno", apellido: "CABRAL" },
  {
    nombre: "Juan Manuel",
    apellido: "CABRERA",
    clubes: [
      { nombre: "Deportivo Morón" },
      { nombre: "Sarmiento (Junín)" },
      { nombre: "Argentinos Juniors" },
      { nombre: "UAI Urquiza" },
      { nombre: "Flandria" },
    ],
  },
  { nombre: "Leandro", apellido: "CABRERA" },
  { nombre: "Martín", apellido: "CABRERA" },
  { nombre: "Pablo", apellido: "CACERES" },
  { nombre: "Pablo", apellido: "CALDERON" },
  { nombre: "Julián", apellido: "CANO" },
  { nombre: "Jonathan", apellido: "CAÑETE" },
  {
    nombre: "Leonel",
    apellido: "CARDOZO",
    clubes: [{ nombre: "Deportivo Morón" }, { nombre: "Lanús" }],
  },
  { nombre: "Abel", apellido: "CASQUETE" },
  { nombre: "Matías", apellido: "CASTRO" },
  { nombre: "Juan", apellido: "CELAYA" },
  { nombre: "Lucio", apellido: "CERESETTO" },
  { nombre: "Lucas", apellido: "CHACANA" },
  { nombre: "Nahuel", apellido: "CHACON" },
  { nombre: "Diego", apellido: "CHAVES" },
  { nombre: "Daniel", apellido: "CHAVEZ" },
  { nombre: "Esteban", apellido: "CIACCHERI" },
  { nombre: "Mauro", apellido: "CONOCHIARI" },
  {
    nombre: "Elias",
    apellido: "CONTRERAS",
    clubes: [
      { nombre: "Deportivo Morón" },
      { nombre: "Brown (Adrogué)" },
      { nombre: "Estudiantes (Caseros)" },
      { nombre: "Temperley" },
      { nombre: "Güemes" },
      { nombre: "Sportivo Luqueño" },
    ],
  },
  { nombre: "Matías", apellido: "CORDOBA" },
  { nombre: "Maximiliano", apellido: "CORONEL" },
  { nombre: "Santiago", apellido: "CORONEL" },
  {
    nombre: "Matías",
    apellido: "CORTAVE",
    clubes: [
      { nombre: "Deportivo Morón" },
      { nombre: "Carlos Mannucci" },
      { nombre: "Maccabi Herzliya" },
      { nombre: "Brown (Adrogué)" },
      { nombre: "Macará" },
      { nombre: "Quilmes" },
      { nombre: "Almagro" },
    ],
  },
  { nombre: "Tino", apellido: "COSTA" },
  {
    nombre: "Ivo",
    apellido: "COSTANTINO",
    clubes: [
      { nombre: "Deportivo Morón" },
      { nombre: "Danubio" },
      { nombre: "Belgrano" },
      { nombre: "Atlanta" },
      { nombre: "Comunicaciones" },
      { nombre: "Deportivo Español" },
      { nombre: "San Martín (San Juan)" },
    ],
  },
  { nombre: "Lionel", apellido: "COUDANNES" },
  { nombre: "Agustín", apellido: "CURRUHINCA" },
  { nombre: "Ezequiel", apellido: "DANGELO" },
  { nombre: "Mauricio", apellido: "DELCASTILLO" },
  { nombre: "Santiago", apellido: "DEOSSA" },
  {
    nombre: "Federico",
    apellido: "DIAZ",
    clubes: [
      { nombre: "Deportivo Morón" },
      { nombre: "Sportivo Italiano" },
      { nombre: "Brown (Adrogué)" },
      { nombre: "Los Andes" },
      { nombre: "Estudiantes (Caseros)" },
      { nombre: "Desamparados" },
    ],
  },
  { nombre: "Rodrigo", apellido: "DIAZ" },
  {
    nombre: "Lautaro",
    apellido: "DISANTO",
    clubes: [
      { nombre: "Deportivo Morón" },
      { nombre: "CADU (Zárate)" },
      { nombre: "Libertad" },
      { nombre: "Desamparados" },
      { nombre: "Douglas Haig" },
      { nombre: "Villa Mitre" },
      { nombre: "Independiente Rivadavia" },
    ],
  },
  { nombre: "Federico", apellido: "DOMINGUEZ" },
  { nombre: "Tomás", apellido: "DUBEN" },
  { nombre: "Carlos", apellido: "ESCUDERO" },
  {
    nombre: "Juan Cruz",
    apellido: "ESQUIVEL",
    clubes: [
      { nombre: "Deportivo Morón" },
      { nombre: "San Martín (Tucumán)" },
      { nombre: "Patronato" },
      { nombre: "Atlético de Rafaela" },
      { nombre: "Platense" },
      { nombre: "Tigre" },
      { nombre: "Talleres" },
      { nombre: "Gimnasia La Plata" },
    ],
  },
  { nombre: "Nicolás", apellido: "ESQUIU" },
  { nombre: "Diego", apellido: "EZQUERRA" },
  {
    nombre: "Franco",
    apellido: "FAGUNDEZ",
    clubes: [
      { nombre: "Deportivo Morón" },
      { nombre: "Estudiantes (Caseros)" },
      { nombre: "El Linqueño" },
      { nombre: "Peñarol (San Juan)" },
      { nombre: "Deportivo Riestra" },
      { nombre: "Sarmiento (Junín)" },
    ],
  },
  { nombre: "Nicolás", apellido: "FALCZUK" },
  { nombre: "Fabio", apellido: "FARIAS" },
  {
    nombre: "Ramiro",
    apellido: "FERGONZI",
    clubes: [
      { nombre: "Deportivo Morón" },
      { nombre: "Adhyaksa" },
      { nombre: "Persik" },
      { nombre: "Persita" },
      { nombre: "Persipura" },
      { nombre: "Alianza Atlético" },
      { nombre: "Chacarita" },
      { nombre: "Bhayangkara" },
      { nombre: "Zacatepec" },
      { nombre: "Patriotas" },
      { nombre: "Mitre (SdE)" },
      { nombre: "Flandria" },
      { nombre: "Almirante Brown" },
      { nombre: "Deportivo Español" },
      { nombre: "Colegiales" },
      { nombre: "San Felipe" },
    ],
  },
  {
    nombre: "Pablo",
    apellido: "FERREIRA",
    clubes: [
      { nombre: "Deportivo Morón" },
      { nombre: "Platense" },
      { nombre: "Jedinstvo Ub" },
    ],
  },
  { nombre: "Juan", apellido: "FERREIRA" },
  { nombre: "Juan Carlos", apellido: "FERREIRA" },
  { nombre: "Luis", apellido: "FERREYRA" },
  {
    nombre: "Leandro",
    apellido: "FINOCHIETTO",
    clubes: [
      { nombre: "Deportivo Morón" },
      { nombre: "Guaireña" },
      { nombre: "Güemes" },
      { nombre: "Independiente Rivadavia" },
      { nombre: "Argentinos Juniors" },
      { nombre: "Alvarado" },
    ],
  },
  {
    nombre: "Francisco",
    apellido: "FLORES",
    clubes: [
      { nombre: "Deportivo Morón" },
      { nombre: "San Lorenzo" },
      { nombre: "Atlético Tucumán" },
      { nombre: "Quilmes" },
    ],
  },
  { nombre: "Lautaro", apellido: "FORMICA" },
  {
    nombre: "Emiliano",
    apellido: "FRANCO",
    clubes: [
      { nombre: "Deportivo Morón" },
      { nombre: "San Telmo" },
      { nombre: "Tepatitlán" },
      { nombre: "Atlético Grau" },
      { nombre: "Defensores de Belgrano (Villa Ramallo)" },
      { nombre: "Mitre" },
      { nombre: "Sant Julia" },
      { nombre: "Newell's" },
      { nombre: "Oliveirense" },
      { nombre: "Ibiza" },
    ],
  },
  { nombre: "Enzo", apellido: "GALEANO" },
  { nombre: "Bruno", apellido: "GALVAN" },
  {
    nombre: "Bahiano",
    apellido: "GARCIA",
    clubes: [
      { nombre: "Deportivo Morón" },
      { nombre: "Chaco For Ever" },
      { nombre: "Barracas Central" },
      { nombre: "Colegiales" },
      { nombre: "CADU (Zárate)" },
    ],
  },
  { nombre: "Franco", apellido: "GARCIA" },
  { nombre: "Nicolás", apellido: "GASPERI" },
  { nombre: "Emmanuel", apellido: "GIMENEZ" },
  { nombre: "Kevin", apellido: "GISSI" },
  { nombre: "Dylan", apellido: "GLABY" },
  {
    nombre: "Agustín",
    apellido: "GOMEZ",
    clubes: [
      { nombre: "Deportivo Morón" },
      { nombre: "Deportivo Cuenca" },
      { nombre: "Deportivo Garcilaso" },
      { nombre: "Instituto" },
      { nombre: "CADU (Zárate)" },
      { nombre: "Fénix" },
      { nombre: "AIK" },
    ],
  },
  { nombre: "Facundo", apellido: "GOMEZ" },
  { nombre: "Matías", apellido: "GOMEZ" },
  {
    nombre: "Gastón",
    apellido: "GONZALEZ",
    clubes: [
      { nombre: "Deportivo Morón" },
      { nombre: "Platanias Chania" },
      { nombre: "Independiente Rivadavia" },
      { nombre: "Episkopi Rethymno" },
      { nombre: "Chania" },
      { nombre: "Trikala" },
      { nombre: "Apollon Smyrni" },
      { nombre: "Belgrano" },
      { nombre: "Ferro Carril Oeste" },
      { nombre: "Platense" },
    ],
  },
  {
    nombre: "Maximiliano",
    apellido: "GONZALEZ",
    clubes: [
      { nombre: "Deportivo Morón" },
      { nombre: "Atlanta" },
      { nombre: "San Martín (San Juan)" },
      { nombre: "Independiente Rivadavia" },
      { nombre: "Rosario Central" },
      { nombre: "Rangers de Talca" },
      { nombre: "Quilmes" },
      { nombre: "Alvarado" },
      { nombre: "Tigre" },
    ],
  },
  {
    nombre: "Yair",
    apellido: "GONZALEZ",
    clubes: [
      { nombre: "Deportivo Morón" },
      { nombre: "Boston River" },
      { nombre: "Argentinos Juniors" },
      { nombre: "Sud América" },
      { nombre: "La Calera" },
      { nombre: "Chacarita" },
    ],
  },
  { nombre: "Laureano", apellido: "GRANDIS" },
  { nombre: "Martin", apellido: "GRANERO" },
  { nombre: "Matías", apellido: "GUAYARE" },
  { nombre: "Luciano", apellido: "GUAYCOCHEA" },
  { nombre: "Manuel", apellido: "GUIÑAZU" },
  { nombre: "Leandro", apellido: "GUZMAN" },
  {
    nombre: "Nicolás",
    apellido: "HENRY",
    clubes: [
      { nombre: "Deportivo Morón" },
      { nombre: "Tristán Suárez" },
      { nombre: "Monagas" },
      { nombre: "Flandria" },
      { nombre: "Douglas Haig" },
    ],
  },
  { nombre: "Leonardo", apellido: "IGLESIAS" },
  {
    nombre: "Emanuel",
    apellido: "IÑIGUEZ",
    clubes: [
      { nombre: "Deportivo Morón" },
      { nombre: "Aldosivi" },
      { nombre: "Monagas" },
    ],
  },
  { nombre: "Maximiliano", apellido: "JEREZ" },
  { nombre: "Gonzalo", apellido: "JUAREZ" },
  {
    nombre: "Santiago",
    apellido: "KUBISZYN",
    clubes: [
      { nombre: "Deportivo Morón" },
      { nombre: "Deportivo Merlo" },
      { nombre: "Orense" },
    ],
  },
  { nombre: "Luciano", apellido: "LAPETINA" },
  { nombre: "Thiago", apellido: "LAURO" },
  { nombre: "Agustín", apellido: "LAVEZZI" },
  {
    nombre: "Emilio",
    apellido: "LAZZA",
    clubes: [
      { nombre: "Deportivo Morón" },
      { nombre: "Olimpo" },
      { nombre: "Güemes" },
      { nombre: "Gimnasia (Conc. del Uruguay)" },
      { nombre: "Atlético Paraná" },
    ],
  },
  { nombre: "Matías", apellido: "LEDESMA" },
  { nombre: "Fabricio", apellido: "LENCI" },
  {
    nombre: "Mateo",
    apellido: "LEVATO",
    clubes: [
      { nombre: "Deportivo Morón" },
      { nombre: "Ferro Carril Oeste" },
      { nombre: "Patronato" },
      { nombre: "Delfín" },
      { nombre: "Universidad de Concepción" },
      { nombre: "Montevideo Wanderers" },
      { nombre: "Los Andes" },
    ],
  },
  { nombre: "Armando", apellido: "LEZCANO" },
  { nombre: "Cristian", apellido: "LILLO" },
  {
    nombre: "Joaquin",
    apellido: "LIVERA",
    clubes: [
      { nombre: "Deportivo Morón" },
      { nombre: "Boca Unidos" },
      { nombre: "Ferro (Gral. Pico)" },
    ],
  },
  { nombre: "Brian", apellido: "LOPEZ" },
  {
    nombre: "Facundo",
    apellido: "LOPEZ",
    clubes: [
      { nombre: "Deportivo Morón" },
      { nombre: "Huracán CR" },
      { nombre: "Comunicaciones" },
    ],
  },
  { nombre: "Luis", apellido: "LOPEZ" },
  { nombre: "Kevin Josue", apellido: "LOPEZ" },
  { nombre: "Ramiro", apellido: "LOPEZ" },
  { nombre: "Kevin", apellido: "LOPEZ" },
  {
    nombre: "Franco",
    apellido: "LORENZON",
    clubes: [
      { nombre: "Deportivo Morón" },
      { nombre: "Estudiantes (Caseros)" },
      { nombre: "Nueva Chicago" },
      { nombre: "San Lorenzo" },
      { nombre: "Deportivo Merlo" },
    ],
  },
  {
    nombre: "Brian",
    apellido: "MACHUCA",
    clubes: [
      { nombre: "Deportivo Morón" },
      { nombre: "Liniers" },
      { nombre: "Güemes" },
      { nombre: "Almagro" },
      { nombre: "Temperley" },
      { nombre: "Oaxaca" },
      { nombre: "Almirante Brown" },
    ],
  },
  { nombre: "Matías", apellido: "MANSILLA" },
  { nombre: "Agustín", apellido: "MANSILLA" },
  { nombre: "Nicolas", apellido: "MARTINEZ" },
  { nombre: "Gerardo", apellido: "MARTINEZ" },
  { nombre: "Román", apellido: "MARTINEZ" },
  { nombre: "Sebastián", apellido: "MARTINEZ" },
  { nombre: "Mariano Matías", apellido: "MARTINEZ" },
  { nombre: "Marcelo", apellido: "MARTINEZ" },
  { nombre: "Emiliano", apellido: "MAYOLA" },
  { nombre: "Emiliano", apellido: "MENDEZ" },
  { nombre: "Júnior", apellido: "MENDIETA" },
  { nombre: "Mariano", apellido: "MESSERA" },
  { nombre: "Alejandro", apellido: "MIGLIARDI" },
  { nombre: "Nicolás", apellido: "MINICI" },
  { nombre: "Braian", apellido: "MOLINA" },
  { nombre: "Sebastián", apellido: "MONTERO" },
  {
    nombre: "Fernando",
    apellido: "MOREYRA",
    clubes: [
      { nombre: "Deportivo Morón" },
      { nombre: "Patronato" },
      { nombre: "Limache" },
      { nombre: "Agropecuario" },
      { nombre: "Villa Dálmine" },
      { nombre: "Deportivo Maipú" },
      { nombre: "Sportivo Belgrano" },
      { nombre: "San Jorge" },
      { nombre: "Kristianstad" },
      { nombre: "Tiro Federal" },
      { nombre: "Gimnasia (Jujuy)" },
    ],
  },
  { nombre: "Santiago", apellido: "NAGUEL" },
  { nombre: "Matías", apellido: "NIZZO" },
  { nombre: "Patricio", apellido: "NUÑEZ" },
  { nombre: "Damián", apellido: "NUÑEZ" },
  {
    nombre: "Juan Manuel",
    apellido: "OLIVARES",
    clubes: [
      { nombre: "Deportivo Morón" },
      { nombre: "Defensores de Belgrano" },
      { nombre: "Brown (Adrogué)" },
      { nombre: "Aldosivi" },
      { nombre: "Crucero del Norte" },
      { nombre: "Quilmes" },
      { nombre: "Olimpo" },
      { nombre: "Everton" },
      { nombre: "Los Andes" },
      { nombre: "Deportivo Merlo" },
      { nombre: "Platense" },
    ],
  },
  { nombre: "Francisco", apellido: "OLIVER" },
  { nombre: "Agustín", apellido: "ONOFRIO" },
  { nombre: "Brian", apellido: "OROSCO" },
  { nombre: "Cristian", apellido: "ORTIZ" },
  { nombre: "Ariel", apellido: "OTERMIN" },
  { nombre: "Germán", apellido: "PACHECO" },
  { nombre: "Jonathan", apellido: "PAEZ" },
  { nombre: "Norberto", apellido: "PALMIERI" },
  { nombre: "Matías", apellido: "PARDO" },
  { nombre: "Maximiliano", apellido: "PAREDES" },
  { nombre: "Cristian", apellido: "PAZ" },
  { nombre: "Cristian", apellido: "PELOZO" },
  { nombre: "Valentín", apellido: "PERALES" },
  { nombre: "Juan Pablo", apellido: "PERALTA" },
  { nombre: "Sebastian", apellido: "PERATTA" },
  { nombre: "Sergio", apellido: "PEREYRA" },
  { nombre: "Javi", apellido: "PEREZ" },
  { nombre: "Sebastian", apellido: "PEREZ" },
  { nombre: "Javier", apellido: "PEREZ" },
  { nombre: "Lucas", apellido: "PEREZGODOY" },
  {
    nombre: "Hernán",
    apellido: "PERRONE",
    clubes: [
      { nombre: "Deportivo Morón" },
      { nombre: "Almirante Brown" },
      { nombre: "Dock Sud" },
    ],
  },
  { nombre: "Lucas", apellido: "POLETTO" },
  { nombre: "Sergio", apellido: "PONCE" },
  { nombre: "Federico", apellido: "PRADA" },
  { nombre: "Facundo", apellido: "PUMPIDO" },
  { nombre: "Franco", apellido: "RACCA" },
  {
    nombre: "Leonel",
    apellido: "RAMIREZ",
    clubes: [{ nombre: "Deportivo Morón" }],
  },
  {
    nombre: "Tomás",
    apellido: "RAMIREZ",
    clubes: [
      { nombre: "Deportivo Morón" },
      { nombre: "Deportes Limache" },
      { nombre: "Central Córdoba (Rosario)" },
    ],
  },
  { nombre: "Nicolás", apellido: "RAMIREZ" },
  { nombre: "Leonardo", apellido: "RAMOS" },
  { nombre: "Ezequiel", apellido: "RESCALDANI" },
  { nombre: "Lucas", apellido: "RODRIGUEZPAGANO" },
  {
    nombre: "Juan Martín",
    apellido: "ROJAS",
    clubes: [
      { nombre: "Deportivo Morón" },
      { nombre: "Villa Dálmine" },
      { nombre: "Colegiales" },
      { nombre: "Delfín" },
      { nombre: "Instituto" },
    ],
  },
  { nombre: "Federico", apellido: "ROJAS" },
  { nombre: "Matías", apellido: "ROMERO" },
  { nombre: "Javier", apellido: "ROSSI" },
  {
    nombre: "Agustín",
    apellido: "RUFINETTI",
    clubes: [
      { nombre: "Deportivo Morón" },
      { nombre: "Ciudad Bolívar" },
      { nombre: "San Telmo" },
      { nombre: "Unión (S)" },
    ],
  },
  { nombre: "Santiago", apellido: "SALA" },
  { nombre: "Gonzalo", apellido: "SALEGA" },
  {
    nombre: "Julio",
    apellido: "SALVÁ",
    clubes: [
      {
        nombre: "Estudiantes (Caseros)",
        desde: "2013",
        hasta: "2013",
        stats: {
          partidos: 1,
          goles: 0,
          asistencias: 0,
          amarillas: 0,
          rojas: 0,
        },
      },
      {
        nombre: "Acassuso",
        desde: "2014",
        hasta: "2014",
        stats: {
          partidos: 2,
          goles: 0,
          asistencias: 0,
          amarillas: 0,
          rojas: 0,
        },
      },
      {
        nombre: "Deportivo Morón",
        desde: "2017",
        hasta: "2021",
        stats: {
          partidos: 40,
          goles: 0,
          asistencias: 0,
          amarillas: 1,
          rojas: 1,
        },
      },
      {
        nombre: "Güemes",
        desde: "2021",
        hasta: "2021",
        stats: {
          partidos: 34,
          goles: 0,
          asistencias: 0,
          amarillas: 1,
          rojas: 0,
        },
      },
      {
        nombre: "Atlético de Rafaela",
        desde: "2022",
        hasta: "2022",
        stats: {
          partidos: 35,
          goles: 0,
          asistencias: 0,
          amarillas: 2,
          rojas: 1,
        },
      },
      {
        nombre: "Patronato",
        desde: "2023",
        hasta: "2024",
        stats: {
          partidos: 74,
          goles: 0,
          asistencias: 0,
          amarillas: 5,
          rojas: 0,
        },
      },
      {
        nombre: "Deportivo Morón",
        desde: "2025",
        hasta: "2026",
        stats: {
          partidos: 44,
          goles: 0,
          asistencias: 0,
          amarillas: 5,
          rojas: 0,
        },
      },
    ],
    posicion: "Arquero",
    posicionDetalle: "Portero",
    fechaNacimiento: "1987-05-18",
    pais: "Argentina",
    ciudad: "Tres Lomas",
    altura: 188,
    pie: "Derecho",
    statsTotales: {
      partidos: 230,
      goles: 0,
      asistencias: 0,
      amarillas: 14,
      rojas: 2,
    },
    statsTotalesMoron: {
      partidos: 84,
      goles: 0,
      asistencias: 0,
      amarillas: 6,
      rojas: 1,
    },
  },
  { nombre: "Alan", apellido: "SALVADOR" },
  {
    nombre: "Braian",
    apellido: "SALVARESCHI",
    clubes: [
      { nombre: "Deportivo Morón" },
      { nombre: "Sarmiento (Junín)" },
      { nombre: "Godoy Cruz" },
      { nombre: "Barracas Central" },
      { nombre: "San Antonio Bulo Bulo" },
      { nombre: "The Strongest" },
    ],
  },
  {
    nombre: "Fabricio",
    apellido: "SANGUINETTI",
    clubes: [
      { nombre: "Deportivo Morón" },
      { nombre: "Inter Bogotá" },
      { nombre: "Patronato" },
      { nombre: "Pirata" },
      { nombre: "Libertad" },
      { nombre: "Atenas" },
    ],
  },
  { nombre: "Rodrigo", apellido: "SAYAVEDRA" },
  { nombre: "Ezequiel", apellido: "SCHELOTTO" },
  { nombre: "Alan", apellido: "SCHONFELD" },
  {
    nombre: "Mauro",
    apellido: "SCHONFELD",
    clubes: [{ nombre: "Deportivo Morón" }, { nombre: "Dock Sud" }],
  },
  { nombre: "Diego", apellido: "SOSA" },
  { nombre: "Matías", apellido: "TABAK" },
  { nombre: "Damián", apellido: "TOLEDO" },
  {
    nombre: "Franco",
    apellido: "TOLOZA",
    clubes: [
      { nombre: "Deportivo Morón" },
      { nombre: "All Boys" },
      { nombre: "Ferro Carril Oeste" },
      { nombre: "Temperley" },
      { nombre: "San Martín (San Juan)" },
      { nombre: "Águila" },
      { nombre: "Tristán Suárez" },
    ],
  },
  { nombre: "Diego", apellido: "TONETTO" },
  { nombre: "Santiago", apellido: "UBEDA" },
  {
    nombre: "Gerónimo",
    apellido: "ULIBARRI",
    clubes: [{ nombre: "Deportivo Morón" }],
  },
  {
    nombre: "Iván",
    apellido: "VAQUERO",
    clubes: [{ nombre: "Deportivo Morón" }],
  },
  { nombre: "Imanol", apellido: "VARELA" },
  {
    nombre: "Franco",
    apellido: "VAZQUEZ",
    clubes: [{ nombre: "Deportivo Morón" }, { nombre: "Argentinos Juniors" }],
  },
  { nombre: "Marcelo", apellido: "VEGA" },
  { nombre: "Nisim", apellido: "VERGARA" },
  { nombre: "Franco", apellido: "VERON" },
  { nombre: "Marcelo", apellido: "VIEYTES" },
  { nombre: "Guillermo", apellido: "VILLALBA" },
  {
    nombre: "Julián",
    apellido: "VITALE",
    clubes: [
      { nombre: "Deportivo Morón" },
      { nombre: "Alvarado" },
      { nombre: "Almagro" },
      { nombre: "San Martín (Tucumán)" },
      { nombre: "Unión" },
    ],
  },
  { nombre: "Sergio Ariel", apellido: "VITURRO" },
  { nombre: "Cristian", apellido: "YASSOGNA" },
  {
    nombre: "Joaquín",
    apellido: "ZAPPACOSTA",
    clubes: [
      { nombre: "Deportivo Morón" },
      { nombre: "Angostura" },
      { nombre: "Hercílio Luz" },
    ],
  },
  { nombre: "Tobías", apellido: "ZARATE" },
  { nombre: "Dante", apellido: "ZUÑIGA" },
];
